export const SET_OFFERS_LIST = "SET_OFFERS_LIST";
export const ADD_OFFER = "ADD_OFFER";
export const UPDATE_OFFER = "UPDATE_OFFER";

export const CURRENT_OFFER_ID = "CURRENT_OFFER_ID";

export const SET_FORM_TYPE = "SET_FORM_TYPE";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_EMAIL = "CHANGE_EMAIL";

export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const DELETE_USER_TOKEN = "DELETE_USER_TOKEN";
export const OFFERS_FILTER = "OFFERS_FILTER";